### ISSUE TITLE
How to reset a specific fields validation state

### ISSUE THREAD

**Issue by seandelaney** [tkrotoff/react-form-with-constraints#27]
I want to clear a specific fields validation state but cant see anything in the docs to do this. I've looked at other issues but cant figure it out.

Is it possible?

I've tried this but I get "this.form.fieldsStore.updateField is not a function":

```
this.form.fieldsStore.updateField('startTime', {
	dirty: false,
	infos: new Set(),
	errors: new Set(),
	warnings: new Set(),
	validationMessage: '',
});
```

**Comment by tkrotoff** [comment]
Good question!

There is a global reset() method if one wants to implement a "form reset button". I didn't have the use case for passing a specific list of fields.
Can you explain the use case/give an example? I'm interested.

How reset() currently works with v0.9.2:

it calls `this.fieldsStore.clearFieldsValidations()`:
https://github.com/tkrotoff/react-form-with-constraints/blob/01b8cac95e6e9115a4a49c4c5f2e22008139abb3/packages/react-form-with-constraints/src/FormWithConstraints.tsx#L174-L177

and `emitResetEvent()` that re-initializes all FieldFeedback state (thus re-render all FieldFeedback):
https://github.com/tkrotoff/react-form-with-constraints/blob/01b8cac95e6e9115a4a49c4c5f2e22008139abb3/packages/react-form-with-constraints/src/FieldFeedback.tsx#L196-L201

`FieldsStore.clearFieldsValidations()` implementation:
https://github.com/tkrotoff/react-form-with-constraints/blob/01b8cac95e6e9115a4a49c4c5f2e22008139abb3/packages/react-form-with-constraints/src/FieldsStore.ts#L12-L14

`Field.clearValidations()` implementation:
https://github.com/tkrotoff/react-form-with-constraints/blob/01b8cac95e6e9115a4a49c4c5f2e22008139abb3/packages/react-form-with-constraints/src/Field.ts#L20-L22

<br><br>
Passing fields to `reset()` would make it symmetric with `validateFields(...inputsOrNames)`: https://github.com/tkrotoff/react-form-with-constraints/blob/01b8cac95e6e9115a4a49c4c5f2e22008139abb3/packages/react-form-with-constraints/src/FormWithConstraints.tsx#L61-L65

<br><br><br>
Currently (v0.9.2) reset a specific field can be done like this:
```JS
const fields = await this.form.validateFields(target); // Here fields is an array of 1 element
fields.forEach(field => field.clearValidations());
this.form.emitResetEvent(); // Force re-render all FieldFeedback
```
or
```JS
const field = this.form.fieldsStore.getField('myField');
field.clearValidations();
this.form.emitResetEvent(); // Force re-render all FieldFeedback
```

**Comment by seandelaney** [comment]
Thanks for all the info above. I was running 0.8.0 but just upgraded to 0.9.2.

I'm building a rota scheduling tool and the shift manage form has start and end time fields which are driven off a start date field. I validate the form on submit but I also validate the form fields individually on blur (with debounce). Auto complete is allowed so I added a global `change` event listener as the form wasn't triggering validation when using auto complete. I dunno if that was HTML5 related or this library but either way, it wasn't working. 

Anyways, the reason for my question was that when a user tried to create a new shift, 
leaving the start date as default. Selecting a start time. Then changing the start date (which would reset the start time again) and this would trigger validation on the start time field even though it had a valid value... It's also kinda hard to explain TBH but I figured if I could reset a specific field, then the issue would be fixed.

**Comment by seandelaney** [comment]
The snippets above worked perfectly though so thank you for explaining how reset worked.

**Comment by tkrotoff** [comment]
Can you explain the use case/give an example? I'm interested. If the use case is interesting/valid I will support it directly. Thx

**Comment by tkrotoff** [comment]
I've released v0.10.0 that adds `resetFields(...inputsOrNames: Array<Input | string>): Promise<Field[]>` because I've bumped into a use case that needed it.
